logging:
  level:
    root: INFO
    com.example: DEBUG   
    org.springframework.web: WARN
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
server:
  port: 9090
  address: 0.0.0.0
spring:
  data:
    mongodb:
      uri: mongodb+srv://DevWork:DevWork@devwork.9mshdom.mongodb.net/JapanSim?retryWrites=true&w=majority&appName=JapanSim
  web:
    resources:
      static-locations: file:/home/record/
# application.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
app:
  jwt:
    secret: "FxeXkZGX29XbExKcC8+b0KxeZDzF6Q5DWzIqenGvA5k="
    access-exp-ms: 600000         # 10 phút
    refresh-exp-ms: 604800000     # 7 ngày

