logging:
  level:
    root: INFO
    com.example: DEBUG   
    org.springframework.web: WARN
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://DevWork:DevWork@devwork.9mshdom.mongodb.net/JapanSim?retryWrites=true&w=majority&appName=JapanSim
# application.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
